spring:
  datasource.url : jdbc:h2:mem:testdb;NON_KEYWORDS=USER
  h2.console.enabled: true
  data.jpa.repositories.bootstrap-mode: default
  jpa:
    defer-datasource-initialization: true
    show-sql: true